repos:
-   repo: local
    hooks:
    -   id: django-test
        name: django-test
        stages: [push]
        entry: python webapp_tracet/manage.py test
        always_run: true
        pass_filenames: false
        language: system
    -   id: pytest
        name: pytest
        stages: [push]
        entry: python -m pytest -s
        always_run: true
        pass_filenames: false
        language: system

# -   repo: https://github.com/psf/black
#     rev: 22.10.0
#     hooks:
#     -   id: black