[
{
    "model": "trigger_app.telescopeprojectid",
    "pk": 2,
    "fields": {
        "id": "C3374",
        "password": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDU0lSTyBBc3Ryb25vbXkgYW5kIFNwYWNlIFNjaWVuY2UiLCJzdWIiOiJBVENBIFJhcGlkIFJlc3BvbnNlIE1vZGUiLCJpYXQiOjE2NDk4OTcxNjUsInByb2plY3RDb2RlIjoiQzMzNzQiLCJzZW1lc3RlciI6IjIwMjJBUFIiLCJuYmYiOjE2NDg3MzE2MDAsImV4cCI6MTY2NDU0NjQwMCwicGlOYW1lIjoiQW5kZXJzb24iLCJwcm9qZWN0VGl0bGUiOiJBVENBIFJhcGlkLVJlc3BvbnNlIGFuZCBNb25pdG9yaW5nIEZvbGxvdy11cCBvZiBIRVNTLWRldGVjdGVkIFRlViBHYW1tYS1yYXkgQnVyc3RzIiwicmVxdWVzdGVkVGltZSI6MTIwLjAsInRlc3QiOnRydWV9.obSnu9yFzsm8_ZBGyWNT736k1YuDduIfi_jZc2cQ_4A",
        "description": "Testing ATCA",
        "telescope": "ATCA",
        "atca_email": "gemma.anderson@curtin.edu.au",
    }
},
{
    "model": "trigger_app.proposalsettings",
    "pk": 2,
    "fields": {
        "telescope": "ATCA",
        "project_id": "C3374",
        "proposal_id": "TEST_ATCA",
        "proposal_description": "Testing ATCA",
        "event_telescope": null,
        "event_min_duration": 0.256,
        "event_max_duration": 1.024,
        "pending_min_duration_1": 1.025,
        "pending_max_duration_1": 2.056,
        "pending_min_duration_2": 0.128,
        "pending_max_duration_2": 0.255,
        "fermi_prob": 50.0,
        "swift_rate_signf": 0.0,
        "repointing_limit": 0.0001,
        "mwa_horizon_limit": 10.0,
        "testing": true,
        "source_type": "GRB",
        "atca_band_4cm": true,
        "atca_band_4cm_exptime": 20,
        "atca_band_4cm_freq1": 5500,
        "atca_band_4cm_freq2": 9000,
        "atca_band_7mm": true,
        "atca_band_7mm_exptime": 20,
        "atca_band_7mm_freq1": 40000,
        "atca_band_7mm_freq2": 45000,
        "atca_max_exptime": 600,
        "atca_min_exptime": 60,
        "atca_prioritise_source": false,
        "atca_dec_max_1": -10,
        "atca_dec_min_1": -90,
        "atca_dec_max_2": 5,
        "atca_dec_min_2": -5,
    }
},
]