[
{
    "model": "trigger_app.telescopeprojectid",
    "pk": 1,
    "fields": {
        "id": "T001",
        "password": "TestingOnly",
        "description": "Testing MWA",
        "telescope": "MWA_VCS",
    }
},
{
    "model": "trigger_app.proposalsettings",
    "pk": 1,
    "fields": {
        "telescope": "MWA_VCS",
        "project_id": "T001",
        "proposal_id": "EARLY_LVC_MWA",
        "proposal_description": "Test sub array on early LVC",
        "event_telescope": null,
        "event_any_duration": false,
        "event_min_duration": 0.256,
        "event_max_duration": 1.024,
        "pending_min_duration_1": 1.025,
        "pending_max_duration_1": 2.056,
        "pending_min_duration_2": 0.128,
        "pending_max_duration_2": 0.255,
        "fermi_prob": 50.0,
        "early_observation_time_seconds": 900,
        "maximum_observation_time_seconds": 7200,
        "maximum_binary_black_hole_probability": 1,
        "maximum_binary_neutron_star_probability": 1,
        "maximum_neutron_star_black_hole_probability": 1,
        "maximum_neutron_star_probability": 1,
        "maximum_terrestial_probability": 0.85,
        "minimum_binary_black_hole_probability": 0,
        "minimum_binary_neutron_star_probability": 0,
        "minimum_neutron_star_black_hole_probability": 0,
        "minimum_neutron_star_probability": 0.01,
        "minimum_terrestial_probability": 0,
        "observe_significant": true,
        "start_observation_at_high_sensitivity": true,
        "maximum_hess_significance": 1,
        "minimum_hess_significance": 0.2,
        "priority": 1,
        "swift_rate_signf": 0.0,
        "repointing_limit": 10.0,
        "mwa_horizon_limit": 10.0,
        "testing": "REAL_ONLY",
        "source_type": "GW",
        "mwa_freqspecs": "121,24",
        "mwa_exptime": 304,
        "mwa_calexptime": 300.0,
        "mwa_freqres": 40.0,
        "mwa_inttime": 0.5,
        "mwa_sub_alt_NE": 90.0,
        "mwa_sub_az_NE": 0.0,
        "mwa_sub_alt_NW": 66.85,
        "mwa_sub_az_NW": 270.0,
        "mwa_sub_alt_SW": 43.97,
        "mwa_sub_az_SW": 270.0,
        "mwa_sub_alt_SE": 59.35,
        "mwa_sub_az_SE": 219.88
    }
},
]