[
{
    "model": "trigger_app.proposalsettings",
    "pk": 1,
    "fields": {
        "telescope": "MWA_VCS",
        "project_id": "T001",
        "proposal_description": "Testing MWA",
        "event_telescope": null,
        "trig_min_duration": 0.256,
        "trig_max_duration": 1.024,
        "pending_min_duration_1": 1.025,
        "pending_max_duration_1": 2.056,
        "pending_min_duration_2": 0.128,
        "pending_max_duration_2": 0.255,
        "fermi_prob": 50.0,
        "swift_rate_signf": 0.0,
        "repointing_limit": 10.0,
        "mwa_horizon_limit": 10.0,
        "testing": true,
        "grb": true,
        "flare_star": false,
        "gw": false,
        "neutrino": false,
        "mwa_freqspecs": "121,24",
        "mwa_nobs": 1,
        "mwa_exptime": 800,
        "mwa_calexptime": 300.0,
        "mwa_freqres": 40.0,
        "mwa_inttime": 0.5,
        "atca_band_3mm": false,
        "atca_band_3mm_freq1": null,
        "atca_band_3mm_freq2": null,
        "atca_band_7mm": false,
        "atca_band_7mm_freq1": null,
        "atca_band_7mm_freq2": null,
        "atca_band_15mm": false,
        "atca_band_15mm_freq1": null,
        "atca_band_15mm_freq2": null,
        "atca_band_4cm": false,
        "atca_band_4cm_freq1": null,
        "atca_band_4cm_freq2": null,
        "atca_band_16cm": false,
        "atca_freq1": null,
        "atca_freq2": null,
        "atca_nobs": null,
        "atca_exptime": null,
        "atca_calexptime": null
    }
}
]